<a href="https://colab.research.google.com/github/Pritipirojia/AI_Engineering_Tutorial_Notes/blob/main/Dataframe_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DataFrame

dataframe---> Combinaton of Rows and columns ---> 2D data structure

## Dataframes can be created in 3 ways:

1. Lists ---> dataframe
2. Dictionary ---> dataframe
3. read_csv ---> dataframe

In [ ]:
import pandas as pd

In [ ]:
rows=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]
list_data=pd.DataFrame(rows, columns=['a','b','c'])
list_data

    a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [ ]:
list_data.shape

(5, 3)

In [ ]:
### Creating Dictionary

dict_data={'Name':['Amit', 'Yash', 'Vivek'], 'Money':[1,5,7], 'Financial Stress':[1,1,0]}
dict_data

{'Name': ['Amit', 'Yash', 'Vivek'],
 'Money': [1, 5, 7],
 'Financial Stress': [1, 1, 0]}

In [ ]:
### Dictionary ---> dataframe

Dict_dataframe=pd.DataFrame(dict_data)
Dict_dataframe

    Name  Money  Financial Stress
0   Amit      1                 1
1   Yash      5                 1
2  Vivek      7                 0

In [ ]:
### Using read_csv() function

df=pd.read_csv('student_depression_dataset.csv')
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
type(df)

pandas.core.frame.DataFrame

## Data Exploration ---> Attributes & functions for the dataframe

### Attributes

1. shape ---> it provides the info about the (row,column) information about the dataset

Syntax---> df.shape

In [ ]:
df.shape

(10116, 18)

2. dtypes---> it provies the idea about the datatype of all columns with their name and their associated data type will be shown by using dtypes
Syntax---> df.dtypes

In [ ]:
df.dtypes

id                                         int64
Gender                                    object
Age                                      float64
City                                      object
Profession                                object
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                            object
Dietary Habits                            object
Degree                                    object
Have you ever had suicidal thoughts ?     object
Work/Study Hours                         float64
Financial Stress                          object
Family History of Mental Illness          object
Depression                               float64
dtype: object

3. index---> for a dataframe with labelled index we can get the idea about the label just by usng index attribute

In [ ]:
df.index

RangeIndex(start=0, stop=10116, step=1)

4. columns---> it provides the idea about all of the column names of the given dataframe

In [ ]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

5. values---> it provides the idea about the values present row by row inside the dataframe. It always returns a numpy array representing the values of column row by row.

In [ ]:
df.values

array([[2, 'Male', 33.0, ..., '1.0', 'No', 1.0],
       [8, 'Female', 24.0, ..., '2.0', 'Yes', 0.0],
       [26, 'Male', 31.0, ..., '1.0', 'Yes', 0.0],
       ...,
       [51139, 'Male', 22.0, ..., '4.0', 'No', 0.0],
       [51150, 'Male', 30.0, ..., '1.0', 'Yes', 0.0],
       [51158, 'Female', 20.0, ..., nan, nan, nan]], dtype=object)

In [ ]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, "'5-6 hours'", 'Healthy', 'B.Pharm', 'Yes', 3.0, '1.0', 'No',
       1.0], dtype=object)

6. ndim---> it provides the idea about the dimension of the dataframe

In [ ]:
df.ndim

2

7. size---> total number of elements present nside the dataframe, that means all rows * all columns (column1---> 50 rows, column2---> 50 rows, column3---> 70 rows ---> size--->50+50+70=170)

In [ ]:
df.size

182088

### Functions

1. head() ---> gives the top 5 rows (default is 5 but can be changed by passing parameter---> e.g. ---> head(7)---> for top 7 rows)

In [ ]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0

In [ ]:
df.head(9)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,'Less than 5 hours',Healthy,PhD,No,4.0,1.0,No,0.0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0.0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,0.0,1.0,Yes,0.0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1.0

2. tail() ---> gives the bottom 5 rows (default is 5 but can be changed by passing parameter---> e.g. ---> tail(7)---> for bottom 7 rows)

In [ ]:
df.tail()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail(10)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
10106,51115,Male,24.0,Srinagar,Student,2.0,0.0,6.10,1.0,0.0,'7-8 hours',Moderate,B.Com,Yes,9.0,4.0,No,1.0
10107,51123,Male,29.0,Kalyan,Student,5.0,0.0,9.72,3.0,0.0,'7-8 hours',Healthy,MBA,Yes,7.0,4.0,No,1.0
10108,51125,Male,33.0,Bhopal,Student,2.0,0.0,8.74,1.0,0.0,'Less than 5 hours',Moderate,MA,Yes,12.0,1.0,No,0.0
10109,51127,Female,19.0,Delhi,Student,5.0,0.0,6.17,5.0,0.0,'More than 8 hours',Unhealthy,'Class 12',No,1.0,5.0,Yes,1.0
10110,51132,Female,29.0,Delhi,Student,3.0,0.0,9.54,5.0,0.0,'7-8 hours',Unhealthy,M.Ed,Yes,6.0,4.0,No,1.0
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. sample() ---> gives the random 1 row (default is 1 but can be changed by passing parameter---> e.g. ---> sample(7)---> for random 7 rows)

In [ ]:
df.sample()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
7685,38645,Male,27.0,Hyderabad,Student,2.0,0.0,9.79,3.0,0.0,'5-6 hours',Healthy,M.Com,No,9.0,3.0,Yes,0.0

In [ ]:
df.sample(6)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
9268,46748,Female,19.0,Ghaziabad,Student,5.0,0.0,8.95,4.0,0.0,'7-8 hours',Healthy,'Class 12',Yes,4.0,2.0,No,1.0
205,997,Male,20.0,Mumbai,Student,1.0,0.0,8.13,1.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,10.0,1.0,Yes,0.0
6618,33154,Male,30.0,Patna,Student,4.0,0.0,9.33,1.0,0.0,'7-8 hours',Unhealthy,BCA,No,12.0,1.0,No,0.0
5175,26056,Female,32.0,Ludhiana,Student,2.0,0.0,5.74,3.0,0.0,'Less than 5 hours',Healthy,MD,Yes,10.0,3.0,Yes,1.0
7561,38067,Female,21.0,Thane,Student,2.0,0.0,8.94,3.0,0.0,'7-8 hours',Moderate,M.Com,No,7.0,4.0,No,0.0
6824,34287,Male,32.0,Hyderabad,Student,3.0,0.0,7.09,2.0,0.0,'More than 8 hours',Unhealthy,M.Tech,No,3.0,4.0,Yes,1.0

4. info()---> provides the idea about

   i. the datatype of all columns

   ii. number of missing vlues of all columns

   iii. dataframe storage in memory

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10116 entries, 0 to 10115
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     10116 non-null  int64
 1   Gender                                 10116 non-null  object
 2   Age                                    10116 non-null  float64
 3   City                                   10116 non-null  object
 4   Profession                             10116 non-null  object
 5   Academic Pressure                      10115 non-null  float64
 6   Work Pressure                          10115 non-null  float64
 7   CGPA                                   10115 non-null  float64
 8   Study Satisfaction                     10115 non-null  float64
 9   Job Satisfaction                       10115 non-null  float64
 10  Sleep Duration                         10115 non-null  object
 11  Dietary Habits                         10115 non-null  object
 12  Degree                                 10115 non-null  object
 13  Have you ever had suicidal thoughts ?  10115 non-null  object
 14  Work/Study Hours                       10115 non-null  float64
 15  Financial Stress                       10115 non-null  object
 16  Family History of Mental Illness       10115 non-null  object
 17  Depression                             10115 non-null  float64
dtypes: float64(8), int64(1), object(9)
memory usage: 1.4+ MB

5. describe()---> it provides an idea as the mathematical summary of the data ---> minimum, maximum, count, mean, std, 25%, 50%, 75%.
It works for numerical columns.

In [ ]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Depression
count,10116.000000,10116.000000,10115.000000,10115.000000,10115.000000,10115.000000,10115.000000,10115.000000,10115.000000
mean,25490.701562,25.843713,3.132674,0.000494,7.666305,2.921997,0.000692,7.165299,0.582996
std,14680.836952,4.902348,1.387604,0.049715,1.466125,1.362346,0.049713,3.691746,0.493088
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12934.250000,21.000000,2.000000,0.000000,6.280000,2.000000,0.000000,4.000000,0.000000
50%,25380.500000,26.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,1.000000
75%,38192.750000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,1.000000
max,51158.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,1.000000

## Data cleaning
1. Missing values
2. Duplicate
3. Rename the column as well

### Before data cleaning, we must have the idea that whether if the data is having any missing value or not or Any duplicate value or not

1. Missing value or not ---> isnull()

In [ ]:
df.isnull()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10111,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10112,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10113,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10114,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10115,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
df.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        1
Work Pressure                            1
CGPA                                     1
Study Satisfaction                       1
Job Satisfaction                         1
Sleep Duration                           1
Dietary Habits                           1
Degree                                   1
Have you ever had suicidal thoughts ?    1
Work/Study Hours                         1
Financial Stress                         1
Family History of Mental Illness         1
Depression                               1
dtype: int64

In [ ]:
data={'Name':['Amit','Prabhat','Shivy','Juhi'],'Package':[8,10,None,17],'Degree':['btech',None,'mba','mbbs']}
data

{'Name': ['Amit', 'Prabhat', 'Shivy', 'Juhi'],
 'Package': [8, 10, None, 17],
 'Degree': ['btech', None, 'mba', 'mbbs']}

In [ ]:
pd.DataFrame(data)

      Name  Package Degree
0     Amit      8.0  btech
1  Prabhat     10.0   None
2    Shivy      NaN    mba
3     Juhi     17.0   mbbs

In [ ]:
pd.DataFrame(data).isnull()

    Name  Package  Degree
0  False    False   False
1  False    False    True
2  False     True   False
3  False    False   False

In [ ]:
pd.DataFrame(data).isnull().sum()

Name       0
Package    1
Degree     1
dtype: int64

In [ ]:
### using numpy.nan
import numpy as np

data2={'Name':['Amit','Prabhat','Shivy','Juhi'],'Package':[8,10,None,17],'Degree':['btech',None,'mba',np.nan]}
data2

{'Name': ['Amit', 'Prabhat', 'Shivy', 'Juhi'],
 'Package': [8, 10, None, 17],
 'Degree': ['btech', None, 'mba', nan]}

In [ ]:
pd.DataFrame(data2).isnull()

    Name  Package  Degree
0  False    False   False
1  False    False    True
2  False     True   False
3  False    False    True

In [ ]:
pd.DataFrame(data2).isnull().sum()

Name       0
Package    1
Degree     2
dtype: int64

2. duplicate values are present or not ---> duplicated()

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10111    False
10112    False
10113    False
10114    False
10115    False
Length: 10116, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

3. rename()---> Renaming the columns
Syntax---> df.rename(columns={'old_col':'new_col'})

In [ ]:
df.rename(columns={'CGPA':'cgpa'})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,cgpa,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.rename(columns={'cgpa':'CGPA','Age':'Student_age'})

,id,Gender,Student_age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### in order to make sure the changes are pernament we can go with inplace parameter

In [ ]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.rename(columns={'Age':'AGE'}, inplace=True)

In [ ]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1.0
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0.0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0.0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1.0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10111,51133,Female,18.0,Kalyan,Student,5.0,0.0,5.58,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,10.0,5.0,Yes,1.0
10112,51136,Male,27.0,Bhopal,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,B.Pharm,No,7.0,5.0,No,1.0
10113,51139,Male,22.0,Surat,Student,1.0,0.0,8.70,2.0,0.0,'More than 8 hours',Moderate,BSc,No,9.0,4.0,No,0.0
10114,51150,Male,30.0,Kalyan,Student,1.0,0.0,5.69,3.0,0.0,'5-6 hours',Healthy,M.Com,No,12.0,1.0,Yes,0.0
10115,51158,Female,20.0,Lucknow,St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Mathematical Function in Dataframe

axis ---> helps calculate the mathematical calculation row wise or column wise
row-wise--->axis=1
column-wise--->axis=0

1. sum() ---> calculates the sum of all values present in a column

In [ ]:
df.sum() ## gives sum column-wise

TypeError: can only concatenate str (not "int") to str

In [ ]:
df.sum(axis=0)

TypeError: can only concatenate str (not "int") to str

In [ ]:
df.sum(axis=1) ## it is failing because of different datatypes

2. mean() ---> calculates the mean of all values present in a column

In [ ]:
df.mean() ## failing because it has string columns as well

3. min() ---> calculates the minimum of all values present in a column

In [ ]:
df.min()

4. max() ---> calculates the maximum of all values present in a column

In [ ]:
df.max()

5. median() ---> calculates the median of all values present in a column

In [ ]:
df.median() ## failing because it has string columns as well

6. var() ---> calculates the variance of all values present in a column

In [ ]:
df.var() ## failing because it has string columns as well

## for selecting a specific column from a dataframe ---> df['col_name']

In [ ]:
df.sample(5)

In [ ]:
df.columns

In [ ]:
df['Academic Pressure']

In [ ]:
df['AGE'].mean()

## for selecting multiple columns from a dataframe ---> df[['col1','col2','col3',....]]

In [ ]:
df.columns

In [ ]:
data=df[['AGE','CGPA','Sleep Duration','Academic Pressure']]
data

### Select the specific rows of our dataframe ---> loc[] and iloc[]

loc[]---> location---> it fetches the record as per the labelled index location of the value

iloc[]---> integer location---> cannot use labelled index---> it fetches the record as per the integer index location of the value

In [ ]:
df.iloc[1000]

Fetch the records by slicing concept

In [ ]:
df.iloc[0:10]

Fetch the record starting from 8 to all of the records

In [ ]:
df.iloc[8:]

Slicing with skipping values

In [ ]:
df.iloc[::2]

loc[]---> location of the given index

In [ ]:
data={'Name':['Amit','Prabhat','Shivy','Juhi'],'Package':[8,10,24,17],'Degree':['btech','mbbs','mba','mtech']}
data1=pd.DataFrame(data)
data1

### set_index---> it can help with setting a specific column as the index of the dataframe

In [ ]:
data1=data1.set_index('Name')

In [ ]:
data

In [ ]:
data1.loc['Amit']

### Fancy indexing for fetching records

In [ ]:
df.iloc[[1,4,7,9]]

In [ ]:
data1.loc[['Amit','Shivy']]

In [ ]:
data1.loc['Amit'::2]  ## Slicing while skipping 1 value


> ## Note: Even if we are having the labelled index, at the back end the labelled index is also going to have interger indexing only by Python

### Fetching specific riws and columns

Syntax---> for iloc---> df.iloc[row_1:row_n,col_1:col_n]

for loc---> df.loc[row_1:row_n,col_1:col_n]

In [ ]:
df.columns

In [ ]:
## using loc[]
df.loc[0:5,['Gender','CGPA','Study Satisfaction']]

In [ ]:
## using iloc[]
df.iloc[0:8,2:7]

### Dataset---> rows ---> 1000 rows and 5 columns ---> df.iloc[0:1000,0:5]

# Filtering data stored in dataframe for coming up with the important insights

In [ ]:
df.sample(5)

Suppose the requirement is:

student ---> Gender= male, Age<24, city= Pune

In [ ]:
df['Gender']=='Male'

In [ ]:
df[df['Gender']=='Male']

In [ ]:
df[(df['Gender']=='Male') & (df['AGE']<24)]

In [ ]:
df[(df['Gender']=='Male') & (df['AGE']<24) & (df['City']=='Pune')] ##Final query

### Why we must have the insight from dtypes attribute to filter the records

In [ ]:
df.head(3)

In [ ]:
### Students ---> Financial Stress==5.0

df[df['Financial Stress']==5.0]

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
## Previously we were not able to fetch Financial stress==5.0 value as it is stored as object or string value
## Below should be the correct syntax
df[df['Financial Stress']=='5.0']

In [ ]:
df.dtypes

### value_counts() ---> this function is being used to calculate the count of the categorical values and that means what is the count of 1st category, count of 2nd category,.....

For the given column ---> 4 categories ---> count of each category from the column itself

In [ ]:
df['AGE'].value_counts()

In [ ]:
df['City'].value_counts()

In [ ]:
df['Gender'].value_counts()

In [ ]:
df['Gender'].value_counts().plot(kind='pie')

In [ ]:
df['Academic Pressure'].value_counts()

In [ ]:
df['Sleep Duration'].value_counts()

In [ ]:
df['Profession'].value_counts()

In [ ]:
df.dtypes

In [ ]:
df[(df['Profession']=='Teacher') & (df['Depression']==1)]

In [ ]:
df.dtypes

In [ ]:
### Student ---> age=23 gender=male, city=pune, sleep duration 5 to 6 hours,Degree=btech Financial stress = 5.0

df[(df['Profession']=='Student') & (df['Gender']=='Male') & (df['AGE']==23) & (df['City']=='Pune') & (df['Sleep Duration']=='5-6 hours') & (df['Degree']=='B.Tech') & (df['Financial Stress']=='5.0')]

## Not getting any rows in output as there must be some issue with our query

In [ ]:
### Student ---> age=23 gender=male, city=pune, sleep duration 5 to 6 hours,Degree=btech Financial stress = 5.0

data=df[(df['Profession']=='Student') & (df['Gender']=='Male') & (df['AGE']==23) & (df['City']=='Pune')]

In [ ]:
data.shape

In [ ]:
data['Sleep Duration'].value_counts()

In [ ]:
data['Sleep Duration'].unique()

In [ ]:
## our previous query did not work as the issue was with 'Sleep Duration' column as the data was stored in "'5-6 hours'" format which is unusual

df[(df['Profession']=='Student') & (df['Gender']=='Male') & (df['AGE']==23) & (df['City']=='Pune') & (df['Sleep Duration']=="'5-6 hours'") & (df['Degree']=='B.Tech') & (df['Financial Stress']=='5.0')]

### strip()---> helps to remove any additional spaces or bracket or anything you want to remove from your string data

In [ ]:
df['Sleep Duration']=df['Sleep Duration'].str.strip("'")

In [ ]:
df['Sleep Duration'].unique()

In [ ]:
## After using strip()

df[(df['Profession']=='Student') & (df['Gender']=='Male') & (df['AGE']==23) & (df['City']=='Pune') & (df['Sleep Duration']=='5-6 hours') & (df['Degree']=='B.Tech') & (df['Financial Stress']=='5.0')]

In [ ]:
df['Degree']=df['Degree'].str.strip("'")

In [ ]:
df['Degree'].unique()

In [ ]:
df[(df['Profession']=='Student') & (df['Gender']=='Male') & (df['AGE']==23) & (df['City']=='Pune') & (df['Sleep Duration']=='5-6 hours') & (df['Degree']=='B.Tech') & (df['Financial Stress']=='5.0')]

### Adding column

Syntax---> df['New_Column']='Scalar Value'
---> or ---> df['New_Column']=df['col_1']+df['col_2']

In [ ]:
df.sample(5)

In [ ]:
df['Name']='Amit'
df

In [ ]:
df['Bio']=str(df['AGE'])+df['Gender']
df

In [ ]:
df['New Column']=df['Degree']+df['Dietary Habits']
df

### df.drop() ---> Remove a specific column as well

In [ ]:
df=df.drop(columns=['Name','Bio'])

In [ ]:
df=df.drop(columns=['New Column'])
df

### astype()---> change the datatype of a specific column and it helps us out with covering less memory storage

In [ ]:
df.info()

In [ ]:
df['Depression']=df['Depression'].astype('int32')
df['AGE']=df['AGE'].astype('int32')

In [ ]:
df.info()

### category datatype

We can replace string or object data type to categorical to save memory

In [ ]:
df['Gender']=df['Gender'].astype('category')
df.info()

In [ ]:
df.sample(5)

In [ ]:
df['Sleep Duration'].value_counts()

In [ ]:
df[(df['Sleep Duration']=='Less than 5 hours') & (df['Depression']==1)].shape[0]

In [ ]:
df[(df['Sleep Duration']=='7-8 hours') & (df['Depression']==1)].shape[0]

In [ ]:
data=df[df['Depression']==1]
data

In [ ]:
data['Sleep Duration'].value_counts()

##