<a href="https://colab.research.google.com/github/Pritipirojia/AI_Engineering_Tutorial_Notes/blob/main/Feature_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Feature Encoding

#### Feature Encoding ---> converting test data into numeric data to feed the data inside our machine learning model

Ordinal data ---> categorical column categories are going to be in an ordered format
Nominal data ---> there is no order among the categories in the column

Encoder for nominal data ---> One hot encoder
Encoder for Ordinal data ---> Ordinal Encoder
Label Encoder ---> used when output column is categorical

In [1]:
import pandas as pd

In [3]:
bank=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [4]:
bank

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [5]:
bank['Job'].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [6]:
bank['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

tertiary > secondary > primary > unknown

##### Ordinal column ---> Education ---> OrdinalEncoder ---> Input data must be in 2D format
##### Label Encoder ---> Target ---> LabelEncoder
##### Nomial Column ---> Married,...

In [8]:
ordinal_data=bank[['Education']]

In [9]:
target_data=bank[['TARGET']]

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
oe=OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])

In [13]:
ordinal_data=oe.fit_transform(ordinal_data)

In [14]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]])

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()

In [18]:
target_data=le.fit_transform(target_data)

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [19]:
target_data

array([0, 0, 0, ..., 1, 0, 0])

## One Hot Encoder

---> used for nominal data
---> As per total no. of categories ---> total no. of columns of vector for each category

Dependency among the multiple columns of vector of each category (Mlticollinearity) ---> Input ---> needs to be an independent column ---> to remove this, we will write columns should come out as no. of categories-1

In [20]:
bank.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [21]:
nominal_data=bank[['Job','Marital','Marital','Default','Housing','Loan','contact','Month','poutcome']]

In [22]:
nominal_data

,Job,Marital,Marital,Default,Housing,Loan,contact,Month,poutcome
0,management,married,married,no,yes,no,unknown,may,unknown
1,technician,single,single,no,yes,no,unknown,may,unknown
2,entrepreneur,married,married,no,yes,yes,unknown,may,unknown
3,blue-collar,married,married,no,yes,no,unknown,may,unknown
4,unknown,single,single,no,no,no,unknown,may,unknown
...,...,...,...,...,...,...,...,...,...
45206,technician,married,married,no,no,no,cellular,nov,unknown
45207,retired,divorced,divorced,no,no,no,cellular,nov,unknown
45208,retired,married,married,no,no,no,cellular,nov,success
45209,blue-collar,married,married,no,no,no,telephone,nov,unknown
45210,entrepreneur,married,married,no,no,no,cellular,nov,other

In [23]:
bank['poutcome'].value_counts()

poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

In [24]:
bank['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
ohe=OneHotEncoder()

In [27]:
nominal_data=ohe.fit_transform(nominal_data)

In [28]:
nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 406899 stored elements and shape (45211, 43)>

## Feature Scaling

---> we want to keep all the column values in a similar range scale.

### Feature scaling ---> It is the final step of feature engineering where we scale all of the column values on a similar scale range

#### Types of feature scaling:
*   Standardization
*   Normalization

### Standardization ---> It is the type of feature scaling where the scaling is done to keep all of the values in a standard scale range

Standard scale range ---> mean=0 & standard deviation=1

standardization of value= (value-mean)/standard deviation

scikitlearn ---> standardscaler ---> fit_transform

### Normalization ---> values must be scaled down to normal range ---> All the values must be in range of [0,1] ---> Min=0,Max=1 ---> use MinMaxScaler


Normalization of value: (value-min)/(max-min)

### Standardization vs Normalization

*   Standardization is optimal when you are going with distance based algorithm
*   If your data consists of outliers, then standardization is better than normalization. If you your data has too many outliers and if you don't want to remove it, you can standardize the data.
*   Normalization is mostly used for neural networks (deep lerning)
*   In normalization, huge issue will occur if data consists of outliers as in this case minmaxscaler won't provide good overall result
*   Apply normalization where scale uniformity matters like data preprocessing, deep learning for models like tensorflow, pytorch

In [30]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [31]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
ss=StandardScaler()

In [34]:
ss.fit_transform(df[['Age']])

array([[ 1.60696496],
       [ 0.28852927],
       [-0.74738448],
       ...,
       [ 2.92540065],
       [ 1.51279098],
       [-0.37068857]])

In [36]:
numerical_columns=ss.fit_transform(df[['Age','Balance','Day','Duration','Campaign','Pdays','Previous']])

In [37]:
numerical_columns

array([[ 1.60696496,  0.25641925, -1.29847633, ..., -0.56935064,
        -0.41145311, -0.25194037],
       [ 0.28852927, -0.43789469, -1.29847633, ..., -0.56935064,
        -0.41145311, -0.25194037],
       [-0.74738448, -0.44676247, -1.29847633, ..., -0.56935064,
        -0.41145311, -0.25194037],
       ...,
       [ 2.92540065,  1.42959305,  0.14341818, ...,  0.72181052,
         1.43618859,  1.05047333],
       [ 1.51279098, -0.22802402,  0.14341818, ...,  0.39902023,
        -0.41145311, -0.25194037],
       [-0.37068857,  0.52836436,  0.14341818, ..., -0.24656035,
         1.4761376 ,  4.52357654]])

## Column Transformer

This transformer can help us transforming ordinal data, nominal data & numeric data for the independent features without separating the columns from each other.

Parameters:


1.   Name that we provide the current transformer we are using
2.   Original or exact transformer ---> OrdinalEncoder or OneHotCoder or SimpleImputer
3.   Column_name ---> on which column you want to apply transformation


remainder=passthrough ---> it is not applicable for all the numerical column but only for columns which are left out.

In [38]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [39]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [40]:
df.isnull().sum()

Age          0
Job          0
Marital      0
Education    0
Default      0
Balance      0
Housing      0
Loan         0
contact      0
Day          0
Month        0
Duration     0
Campaign     0
Pdays        0
Previous     0
poutcome     0
TARGET       0
dtype: int64

In [41]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [49]:
df.columns

Index(['Age', 'Job', 'Marital', 'Education', 'Default', 'Balance', 'Housing',
       'Loan', 'contact', 'Day', 'Month', 'Duration', 'Campaign', 'Pdays',
       'Previous', 'poutcome', 'TARGET'],
      dtype='object')

In [42]:
transformer=ColumnTransformer(
    transformers=[
        ('tr1',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']]),['Education']),
         ('tr2',OneHotEncoder(),['Job','Marital','Default','Housing','Loan','contact','Month','poutcome'])]
        ,remainder='passthrough')

In [43]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1',
                                 OrdinalEncoder(categories=[['unknown',
                                                             'primary',
                                                             'secondary',
                                                             'tertiary']]),
                                 ['Education']),
                                ('tr2', OneHotEncoder(),
                                 ['Job', 'Marital', 'Default', 'Housing',
                                  'Loan', 'contact', 'Month', 'poutcome'])])

In [44]:
x=df.iloc[:,:-1]

In [45]:
x

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [46]:
y=df['TARGET']

In [47]:
y

0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: TARGET, Length: 45211, dtype: object

In [50]:
x=transformer.fit_transform(x)

In [51]:
x

array([[  3.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       ...,
       [  2.,   0.,   0., ...,   5., 184.,   3.],
       [  2.,   0.,   1., ...,   4.,  -1.,   0.],
       [  2.,   0.,   0., ...,   2., 188.,  11.]])

In [52]:
le=LabelEncoder()
y=le.fit_transform(y)

In [53]:
y

array([0, 0, 0, ..., 1, 0, 0])