<a href="https://colab.research.google.com/github/Pritipirojia/AI_Engineering_Tutorial_Notes/blob/main/pandas_series_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

Pandas is a powerful library used for data manipulation and analysis. It helps us to work with data in Tabular format, just like how we deal with data and spreadsheet in excel or data.

Pandas provides functionalities and attributes to clean, organize and analyze large amounts of data

1. Easy to use---> Works like Excel inside python
2. Fast---> Handles large data faster than manual methods
3. Clean data---> helps clean, filter and transform messy data
4. Integrates well---> Matplotlib, Seaborn
5. Ideal for data science, ML and AI

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

Pandas series is a column of data in a table like in excel or google sheets with labels called as indexes attached to each value

In [ ]:
pd.Series(data=[40,50,60],index=['Bread', 'Milk', 'Butter'], name='Price of grocery items')

Bread     40
Milk      50
Butter    60
Name: Price of grocery items, dtype: int64

Whenever you create a series, data type is always going to be decided on the basis of the values itself that are there in the series

Series is a 1D array that can hold any type of data like integers, float, string (objects), boolean, mixed data type.

## Creating a series in multiple ways
1. List
2. Numpy array
3. Dictionary
4. custom index
5. scalar value

In [ ]:
## series from list
country=['India', 'china', 'USA', 'Pakistan']
pd.Series(country)

0       India
1       china
2         USA
3    Pakistan
dtype: object

In [ ]:
batsman_runs=[48,64,73,98,65,90]
pd.Series(batsman_runs, dtype='int32')

0    48
1    64
2    73
3    98
4    65
5    90
dtype: int32

In [ ]:
subject_names=['Maths', 'Physics', 'Chemistry', 'English']
subject_marks=[48,92,67,98]

pd.Series(data=subject_marks, index=subject_names, name='Subject Marks data', dtype='int32')

Maths        48
Physics      92
Chemistry    67
English      98
Name: Subject Marks data, dtype: int32

In [ ]:
### Creating an series using a numpy array
values=np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

## Dictionary to Series

Dictionary is another data structure that stores the data in a key value pair and just because it stores the data in a key value pair so we don't have to explicitly mention the index

In [ ]:
data_items={'Maths':78, 'English':92, 'Physics':88, 'Chemistry':64}
pd.Series(data_items)

Maths        78
English      92
Physics      88
Chemistry    64
dtype: int64

In [ ]:
## custom index to Series
values=[1,2,3,4,5]
pd.Series(data=values, index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
## Scalar value inside an Series

pd.Series(4,index=['a','b','c','d','e'])

a    4
b    4
c    4
d    4
e    4
dtype: int64

read_csv()--->this function reads the content from the csv file in pandasso that we can perform the operations on the data or we can perform effective analysis

In [ ]:
Data= pd.read_csv('/content/youtube_2025_dataset_202504061614.csv')

In [ ]:
Data

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [ ]:
## 2nd way as the file is in same folder

youtube=pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [ ]:
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [ ]:
subs=youtube['Total Subscribers']

In [ ]:
subs

0       8264152
1       8768222
2       6163386
3       4712268
4       9592017
         ...
4995    2665835
4996     136992
4997    2314561
4998    6954832
4999    6785166
Name: Total Subscribers, Length: 5000, dtype: int64

## MAthematical functions in Pandas

### 1. sum() ---> sum of all values present in the series

In [ ]:
subs.sum()

np.int64(25292407967)

### 2. product()---> product of all the values in the series

In [ ]:
subs.product()

## output is zero as the product value of all the subscribers is very large

np.int64(0)

In [ ]:
subs.sort_values()

3595       1755
3204       2910
2470       8649
4584       9029
2615       9436
         ...
3969    9991900
380     9992512
1177    9995049
3593    9999559
1931    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

### 3. mean()---> Mean provides us with the average value of the data column

In [ ]:
subs.mean()

np.float64(5058481.5934)

### 4. median()---> Median also provides the idea about the average of the data. for coming up with median , we need to sort the values in ascending order and then the middle value after sorting the data is the median.

In [ ]:
subs.median()

5105967.0

### mode()---> mode provides us with the idea that which value is getting repeated maximum number of times

In [ ]:
subs.mode()

0          1755
1          2910
2          8649
3          9029
4          9436
         ...
4995    9991900
4996    9992512
4997    9995049
4998    9999559
4999    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

In [ ]:
avg=youtube['Avg Video Length (min)']

In [ ]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
avg.mode()

0    24.1
Name: Avg Video Length (min), dtype: float64

### std()---> if I need to get the idea that how the values inside the series are distributed from the average or mean value then we can come up with the standard deviation

In [ ]:
avg.std()

0.8745549483431736

In [ ]:
subs.std()

2890894.947500023

### variance---> variance also provides the insight about the distribution of the data from the mean value. And variance is the square of the standard deviation.

In [ ]:
avg.var()

0.7648463576715311

### min()---> minimum value in the series
### max()---> maximum value in the series

In [ ]:
avg.min()

19.1

In [ ]:
avg.max()

28.9

### describe()---> describe function provides the idea about the summary of the important mathematical calculations for the data

It provides below details:
i. count---> total number of rows
ii. mean--->mean
iii. std---> standard deviation
iv. min--->  minimum value
v. 25% --->25% of the values are less than this specifiv value
vi. 50%	--->50% of the values are less than this specifiv value
vii. 75% --->75% of the values are less than this specifiv value
viii. max	---> maximum value

In [ ]:
avg.describe()

count    5000.000000
mean       24.004540
std         0.874555
min        19.100000
25%        23.500000
50%        24.000000
75%        24.500000
max        28.900000
Name: Avg Video Length (min), dtype: float64

## Indexing in Series (To have the access over the certain value or values)

### 1. Positive indexing (just like list) ---> start from 0 to forward direction
### 2. No negative indexing

In [ ]:
avg[2]

np.float64(24.0)

### 3. Slicing ---> In series we can get the certain values over a given specific range and we can do it using [initial_val:final_val+1]

In [ ]:
avg[7:18]

7     25.6
8     23.1
9     24.2
10    22.9
11    25.4
12    26.9
13    23.4
14    24.1
15    24.9
16    24.7
17    24.8
Name: Avg Video Length (min), dtype: float64

If I want the values skipped as a certain value

In [ ]:
avg[2:12:2]

2     24.0
4     24.6
6     23.2
8     23.1
10    22.9
Name: Avg Video Length (min), dtype: float64

### Reverse values in a series

In [ ]:
avg[::-1]

4999    25.2
4998    24.5
4997    25.2
4996    26.3
4995    22.0
        ...
4       24.6
3       24.6
2       24.0
1       22.9
0       24.8
Name: Avg Video Length (min), Length: 5000, dtype: float64

4. Fancy Indexing---> if I want the specific values from the series than we go with fancy indexing

In [ ]:
avg[[2,4,9]]

2    24.0
4    24.6
9    24.2
Name: Avg Video Length (min), dtype: float64

In [96]:
avg[[55,1008,79,56,69]]

55      24.9
1008    23.3
79      25.1
56      23.0
69      24.0
Name: Avg Video Length (min), dtype: float64

5. Indexing with labels---> A series which is consisting of labels as the index or custom index, then for this data we can retrieve the data using that custom index or label

In [103]:
## DataFrame--> Combination of Multiple Series(Columns)

type(pd.read_csv('youtube_two_column.csv')) ## to know if youtube is a dataframe or not

pandas.core.frame.DataFrame

In [104]:
## Squeeze---> squeeze parameter makes sure that the data is in series format
## index_col
df = pd.read_csv('youtube_two_column.csv', index_col=0).squeeze("columns")
df

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [105]:
type(df)

pandas.core.series.Series

In [ ]:
##Indexing with labels

df['Eric Patel']

np.int64(68)

### Editing Series (Bring the changes into the values stored inside the series)

1. Using Indexing --->df[0]=65---> changing the original value at index 0 to 65

In [ ]:
df['Eric Patel']=60

In [ ]:
df['Eric Patel']

np.int64(60)

### if indexing doesn't exist and you try to change the value, it will add the value with that index to the dataframe

In [92]:
df['Amit kumar Singh']

KeyError: 'Amit kumar Singh'

In [93]:
df['Amit kumar Singh']=78

In [94]:
df

Youtuber Name
Eric Patel             60
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int64

### Slicing in Series ---> df[2:7]=100--->100 will be associated for index 2 to 6

In [95]:
avg[1:5]=28

/tmp/ipykernel_1168/2504678467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  avg[1:5]=28

In [97]:
avg

0       24.8
1       28.0
2       28.0
3       28.0
4       28.0
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

## Fancy indexing ---> df[2,4,8]=[45,84,79]

In [99]:
avg[[4,4998,4996,0]]=[25,21,20,24]

/tmp/ipykernel_1168/2428048921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  avg[[4,4998,4996,0]]=[25,21,20,24]

In [100]:
avg

0       24.0
1       28.0
2       28.0
3       28.0
4       25.0
        ...
4995    22.0
4996    20.0
4997    25.2
4998    21.0
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

## Index Labelling

In [102]:
df[['Eric Patel', 'Jessica Nelson MD','Amit kumar Singh']]=[45,210,200]

## we  will discuss later as it requires loc function

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

## DataFrame--> Combination of Multiple Series(Columns)

## Squeeze---> squeeze parameter makes sure that the data is in series format

Squeeze when csv file has one column

In [107]:
df = pd.read_csv('youtube_one_column.csv').squeeze("columns")
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: object

In [108]:
type(df)

pandas.core.series.Series

Squeeze when csv file has two column

In [111]:
pd.read_csv('youtube_two_column.csv')

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

## index_col (parameter to use when you want to refer to one column as index)

In [113]:
dataframe=pd.read_csv('youtube_two_column.csv', index_col='Youtuber Name').squeeze('columns')

In [114]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

## Attribute in Series

1. .values---> representing only the values of the given series

In [115]:
df.values

array(['Smith-Ross Labs', 'Sandoval PLC Hub',
       'Jones, Moore and Ho Network', ..., 'Obrien-Roberts Studios',
       'King Ltd Hub', 'Henry Ltd Studios'], dtype=object)

In [116]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92])

2. .index---> returns only the index values from the given column

In [117]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [118]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92])

In [120]:
dataframe.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='object', name='Youtuber Name', length=5000)

3. dtype ---> Dtype provides the idea about the data type of the values that you are storing

In [121]:
dataframe.dtype

dtype('int64')

In [122]:
dataframe.astype('int32')

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

4. size ---> this attribute provides the idea about the total number of rows inside the dataset

In [123]:
dataframe.size

5000

5. shape---> no. of rows and columns

In [124]:
dataframe.shape ## it is not giving column as there is only one column in dataframe series

(5000,)

6. ndim ---> dimension of the given dataset

In [125]:
dataframe.ndim

1

7. name ---> provides name of the series

In [126]:
dataframe.name

'Total Videos'

8. is_unique ---> this provides with the idea about whether if unique values are there inside the column

In [127]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [129]:
dataframe.is_unique

False

In [130]:
pd.Series([1,2,3,4,5]).is_unique

True

## Series Methods

1. head() ---> Provides the top preview of Data as the top 5 rows of the dataframe or series. It is quite helpful with providing the preview of the dataset (default is top 5 rows). It if you want to preview top 10 rows then pass 10 as an argument.

In [133]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [132]:
dataframe.head()

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Name: Total Videos, dtype: int64

In [134]:
dataframe.head(7)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Name: Total Videos, dtype: int64

2. tail() ---> Provides the bottom preview of Data as the bottom 5 rows of the dataframe or series. It is quite helpful with providing the preview of the dataset (default is bottom 5 rows). It if you want to preview bottom 10 rows then pass 10 as an argument.

In [135]:
dataframe.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int64

In [136]:
dataframe.tail(7)

Youtuber Name
Howard Phelps     126
Sharon Graham     231
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int64

3. sample() ---> provides any custom row from the dataset for us to preview

In [137]:
dataframe.sample() ## output is one random row

Youtuber Name
Chad Rodriguez    215
Name: Total Videos, dtype: int64

In [139]:
dataframe.sample(5) ## output is 5 random rows

Youtuber Name
Darren Gray         129
Victoria Garrett    367
Jillian Gray        192
Brittany Wong       406
Zachary Phillips    478
Name: Total Videos, dtype: int64

4. value_counts() ---> provides the idea about the count of the values (catagorical values), if i am having a column where the categorical value count I want to calculate then I can go with value_counts()

In [141]:
youtube=pd.read_csv('youtube_2025_dataset_202504061614.csv')
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [143]:
avg=youtube['Avg Video Length (min)']
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [144]:
type(avg)

pandas.core.series.Series

In [145]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
21.2      1
28.0      1
27.3      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

5. sort_values() ---> sorts the values in ascending order

In [147]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

## parameter ---> ascending =false (sorting ---> descending)

In [148]:
avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

## Method chaining ---> we will be using multiple meethods to get the required value in a way the first method's output will be second method input  then second method output will be third method input

In [149]:
avg.sort_values(ascending=False).head()

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
Name: Avg Video Length (min), dtype: float64

In [151]:
avg.sort_values(ascending=False).head(7).values[0]

np.float64(28.9)

In [152]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [156]:
average=avg.copy() ##to use inplace parameter we need to copy the data first
average

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [157]:
### in order to make a change in our data permanent ---> inplace
average.sort_values(inplace=True)
average

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [158]:
average

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

6. sort_index()---> this method sorts the index of the dataset

In [159]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [160]:
dataframe.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int64